/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2016 (13.0.4001)
    Source Database Engine Edition : Microsoft SQL Server Express Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2016
    Target Database Engine Edition : Microsoft SQL Server Express Edition
    Target Database Engine Type : Standalone SQL Server
*/

USE [master]
GO

/****** Object:  Database [TickTaskDoe]    Script Date: 3/14/2018 6:27:18 PM ******/
CREATE DATABASE [TickTaskDoe]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TickTaskDoe', FILENAME = N'C:\Users\pavan\TickTaskDoe.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TickTaskDoe_log', FILENAME = N'C:\Users\pavan\TickTaskDoe_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [TickTaskDoe] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TickTaskDoe].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TickTaskDoe] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TickTaskDoe] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TickTaskDoe] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TickTaskDoe] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TickTaskDoe] SET ARITHABORT OFF 
GO

ALTER DATABASE [TickTaskDoe] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [TickTaskDoe] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TickTaskDoe] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TickTaskDoe] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TickTaskDoe] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TickTaskDoe] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TickTaskDoe] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TickTaskDoe] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TickTaskDoe] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TickTaskDoe] SET  ENABLE_BROKER 
GO

ALTER DATABASE [TickTaskDoe] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TickTaskDoe] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TickTaskDoe] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TickTaskDoe] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TickTaskDoe] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TickTaskDoe] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [TickTaskDoe] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TickTaskDoe] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TickTaskDoe] SET  MULTI_USER 
GO

ALTER DATABASE [TickTaskDoe] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TickTaskDoe] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TickTaskDoe] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TickTaskDoe] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TickTaskDoe] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TickTaskDoe] SET QUERY_STORE = OFF
GO

USE [TickTaskDoe]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [TickTaskDoe] SET  READ_WRITE 
GO


