insert into NationalityGreetings values 
('Saudi Arabia','Ahalan'),
('Bulgeria','Zdrasti'),
('China','Ni Hao'),
('France','Bonjour'),
('Germany','Guten Tag'),
('India','Namaste'),
('Hungary','Jo Napot'),
('Iceland','Gooan Daginn'),
('Indonesia','Halo'),
('Iran','Dia Dhuit'),
('Italy','Salve'),
('Japan','Kon Nichiwa'),
('Korea','Ha Se Yo'),
('Netherlands','Hallo'),
('Poland','Dzein Dobry'),
('Portugal','Ola'),
('Russia','Zdravstvuyte'),
('Spain','Hola'),
('Sweden','Hej'),
('Turkey','Selam'),
('Ukrain','Vitayu'),
('United States','Hello'),
('Vietnam','Xin Chao')